### ISSUE TITLE
Better placement and/or hide on HTML hover

### ISSUE THREAD

**Issue by kevnk** [jorenvanhee/tailwindcss-debug-screens#1]
I've implemented something very similar on a lot of my dev project, but a couple of things I've done differently on mine that may be worth considering:

1. If you place it `bottom: 1.5rem` then it won't get covered up (at least in Chrome) when you hover over links

2. If you hide it on `body:hover` then it never gets in the way of the viewport, but shows while adjusting the viewport width. Obviously, this wouldn't help mobile much, but maybe there's a way to handle that case.

**Comment by kevnk** [comment]
For reference, here's what I typically use on my bootstrap scss projects:

```scss
html.development,
html.local {
  body {
    &:after {
      content: 'xxs #{map-get($grid-breakpoints, xxs)}';
      position: fixed;
      bottom: $spacer;
      left: -3px;
      border-radius: 3px;
      display: inline-block;
      text-align: center;
      background: #000;
      color: #fff;
      font-size: calc(#{$spacer-3} * 0.85);
      line-height: $spacer-3;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial,
        'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol',
        'Noto Color Emoji';
      padding: $spacer-2 $spacer-3;
      z-index: 99999999;
      @include media-breakpoint-up(xs) {
        content: 'xs #{map-get($grid-breakpoints, xs)}';
      }
      @include media-breakpoint-up(sm) {
        content: 'sm #{map-get($grid-breakpoints, sm)}';
      }
      @include media-breakpoint-up(md) {
        content: 'md #{map-get($grid-breakpoints, md)}';
      }
      @include media-breakpoint-up(lg) {
        content: 'lg #{map-get($grid-breakpoints, lg)}';
      }
      @include media-breakpoint-up(xl) {
        content: 'xl #{map-get($grid-breakpoints, xl)}';
      }
    }
  }
  &:hover {
    body:after {
      display: none;
    }
  }
}
```
