### ISSUE TITLE
TailwindCss V4

### ISSUE THREAD

**Issue by StephenThink** [jorenvanhee/tailwindcss-debug-screens#28]
Can I just start by saying thank you for this as it makes working in tailwind easier.

However this doesnt work with [TailwindCss v4](https://tailwindcss.com/) is there any thoughts on making an upgraded version?

**Comment by StephenThink** [comment]
I have done a little bit of work to maybe help people.

If debug-screens is present then this will display a black box with white text showing the breakpoint.

This will only work with default breakpoints.

Hopefully this makes sense to people.

in my body tag i have an if statement for an antlers file.

```
  <body class="bg-think-yellow font-poppins leading-normal text-gray-800
                antialiased
                {{ if environment != 'production' }}debug-screens{{ /if }}
                ">
```

I then have a JS file

```
const debugScreen = () => {
    const debug = document.getElementsByClassName("debug-screens").length;

    if (debug) {


        document.addEventListener("DOMContentLoaded", () => {
            // Create the debug div
            const debugScreen = document.createElement("div");
            debugScreen.id = "debug-screen";
            debugScreen.className =
                "fixed z-20 bottom-0 left-0 p-2 text-white bg-black";
            document.body.appendChild(debugScreen);

            function updateBreakpoint() {
                const width = window.innerWidth;
                let breakpoint = "_"; // Default for < 640px

                if (width >= 1536) breakpoint = "2xl";
                else if (width >= 1280) breakpoint = "xl";
                else if (width >= 1024) breakpoint = "lg";
                else if (width >= 768) breakpoint = "md";
                else if (width >= 640) breakpoint = "sm";

                debugScreen.textContent = breakpoint;
            }

            // Update on load and resize
            updateBreakpoint();
            window.addEventListener("resize", updateBreakpoint);
        });
    }

}

export default debugScreen;

```

basically I then call it in the site.js file.

```
import debugScreen from "./debug-screen.js";

debugScreen();
```

**Comment by TiE23** [comment]
I'm a simple man, so I wrote my replacement as a component for React:

```typescript
export function ScreenBreakDebug() {
  return (
    <div className="fixed bottom-0 left-0 bg-black text-white p-1 text-xs z-[2147483647]">
      {BREAKPOINTS.map(({ className, name }) => (
        <div key={name} className={className}>
          screen: {name}
        </div>
      ))}
    </div>
  );
}

const BREAKPOINTS: { name: string; className: string }[] = [
  { name: "sm", className: "hidden sm:block md:hidden" },
  { name: "md", className: "hidden md:block lg:hidden" },
  { name: "lg", className: "hidden lg:block xl:hidden" },
  { name: "xl", className: "hidden xl:block 2xl:hidden" },
  { name: "2xl", className: "hidden 2xl:block" },
] as const;
```

```typescript
{config.env === Env.DEV && <ScreenBreakDebug />}
```

If you happen to have any custom breakpoints, just put it in the constant.

**Comment by biati-digital** [comment]
A simpler approach, similar to the original implementation, is to create an @utility using Tailwind CSS V4. With this little utility it's no longer required to install the extension

```css
@utility debug-screens {
  &::before {
    position: fixed;
    z-index: 2147483647;
    left: 0;
    bottom: 0;
    padding: .3333333em .5em;
    font-size: 12px;
    line-height: 1;
    background-color: #000;
    color: #fff;
    box-shadow: 0 0 0 1px #fff;
    display: block;

    @variant sm {
      content: "screen: sm";
    }

    @variant md {
      content: "screen: md";
    }

    @variant lg {
      content: "screen: lg";
    }

    @variant xl {
      content: "screen: xl";
    }
  }
}
```

that's it, just add the `debug-screens` class to the body tag.
