### ISSUE TITLE
Custom breakpoints smaller than "sm" overlaps other breakpoints in TailwindCSS v4

### ISSUE THREAD

**Issue by KenTandrian** [jorenvanhee/tailwindcss-debug-screens#31]
Hi @jorenvanhee, thanks for updating the plugin to support TailwindCSS v4!

In prior versions, extending the screens will cause custom breakpoints smaller than "sm" (e.g., "xs") overrule the other ones. The only workaround for this is to override the breakpoints (https://github.com/jorenvanhee/tailwindcss-debug-screens/issues/21).

With the release of Tailwind CSS v4, I don't think overriding screens is working anymore. Now we are using `--breakpoint-*` CSS variables to define the screens, and even if we override the default breakpoints by using `--breakpoint-*: initial;`, the media queries are not ordered as expected.

## Steps to reproduce
1. Install `tailwindcss` v4 in your project (in my case it is Next.js).
2. Install `tailwindcss-debug-screens` v3.
3. Add these configurations in the main CSS file.
```css
@import "tailwindcss";
@plugin "tailwindcss-debug-screens";

@theme {
  --breakpoint-*: initial;
  --breakpoint-xs: 360px;
  --breakpoint-sm: 640px;
  --breakpoint-md: 768px;
  --breakpoint-lg: 1024px;
  --breakpoint-xl: 1280px;
  --breakpoint-2xl: 1536px;
  --breakpoint-3xl: 1920px;
}
```
4. Run the development server.
5. Try to resize the width of the screen.

## Current behavior
These are shown in the screen debug:
| Text | Screen Width |
| --- | --- |
| screen: _ | below 360px |
| screen: xs | 360px to 1919px, overriding all other screens (sm, md, lg, xl, 2xl) |
| screen: 3xl | 1920px and above |

## Expected behavior
The other screens should not be overridden by "xs".

Please take a look at this issue. Thanks!
